# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration
client_id = "a501412486e47d05c32949cd348de62b"
application_url = "https://size-fit-app.onrender.com"
embedded = true
name = "size-fit-app"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products"

[app_proxy]
url = "https://size-fit-app.onrender.com"
subpath = "fit-quiz"
prefix = "apps"

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  topics = [ "shop/redact" ]

[auth]
redirect_urls = [ "https://size-fit-app.onrender.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true
